Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Afghanistan','AFG');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Albania','ALB');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Algeria','ALG');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('American Samoa','ASA');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Andorra','AND');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Angola','ANG');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Antigua and Barbuda','ANT');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Argentina','ARG');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Armenia','ARM');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Aruba','ARU');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Australia','AUS');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Austria','AUT');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Azerbaijan','AZE');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Bahamas','BAH');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Bahrain','BRN');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Bangladesh','BAN');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Barbados','BAR');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Belarus','BLR');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Belgium','BEL');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Belize','BIZ');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Bermuda','BER');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Benin','BEN');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Bhutan','BHU');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Bolivia','BOL');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Bosnia and Herzegovina','BIH');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Botswana','BOT');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Brazil','BRA');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('British Virgin Islands','IVB');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Brunei','BRU');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Bulgaria','BUL');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Burkina Faso','BUR');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Burundi','BDI');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Cambodia','CAM');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Cameroon','CMR');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Canada','CAN');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Cape Verde','CPV');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Cayman Islands','CAY');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Central African Republic','CAF');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Chad','CHA');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Chile','CHI');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('China','CHN');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Colombia','COL');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Comoros','COM');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Congo','CGO');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Congo, Dem Rep','COD');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Cook Islands','COK');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Costa Rica','CRC');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Cote d''Ivoire','CIV');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Croatia','CRO');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Cuba','CUB');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Cyprus','CYP');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Czech Republic','CZE');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Denmark','DEN');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Djibouti','DJI');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Dominica','DMA');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Dominican Republic','DOM');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('East Timor','TLS');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Ecuador','ECU');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Egypt','EGY');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('El Salvador','ESA');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Equatorial Guinea','GEQ');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Eritrea','ERI');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Estonia','EST');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Ethiopia','ETH');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Fiji','FIJ');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Finland','FIN');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('France','FRA');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Gabon','GAB');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Gambia','GAM');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Georgia','GEO');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Germany','GER');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Ghana','GHA');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Greece','GRE');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Grenada','GRN');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Guam','GUM');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Guatemala','GUA');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Guinea','GUI');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Guinea-Bissau','GBS');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Guyana','GUY');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Haiti','HAI');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Honduras','HON');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Hong Kong','HKG');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Hungary','HUN');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Iceland','ISL');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('India','IND');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Indonesia','INA');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Iran','IRI');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Iraq','IRQ');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Ireland','IRL');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Israel','ISR');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Italy','ITA');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Jamaica','JAM');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Japan','JPN');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Jordan','JOR');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Kazakhstan','KAZ');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Kenya','KEN');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Korea, North','PRK');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Korea, South','KOR');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Kuwait','KUW');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Kyrgyzstan','KGZ');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Laos','LAO');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Latvia','LAT');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Lebanon','LIB');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Lesotho','LES');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Liberia','LBR');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Libya','LBA');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Liechtenstein','LIE');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Lithuania','LTU');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Luxembourg','LUX');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Macedonia','MKD');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Madagascar','MAD');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Malawi','MAW');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Malaysia','MAS');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Maldives','MDV');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Mali','MLI');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Malta','MLT');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Mauritania','MTN');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Mauritius','MRI');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Mexico','MEX');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Micronesia','FSM');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Moldova','MDA');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Monaco','MON');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Mongolia','MGL');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Morocco','MAR');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Mozambique','MOZ');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Burma','MYA');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Namibia','NAM');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Nauru','NRU');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Nepal','NEP');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Netherlands','NED');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Netherlands Antilles','AHO');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('New Zealand','NZL');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Nicaragua','NCA');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Niger','NIG');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Nigeria','NGR');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Norway','NOR');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Oman','OMA');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Pakistan','PAK');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Palau','PLW');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Palestine, Occupied Territories','PLE');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Panama','PAN');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Papua New Guinea','PNG');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Paraguay','PAR');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Peru','PER');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Philippines','PHI');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Poland','POL');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Portugal','POR');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Puerto Rico','PUR');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Qatar','QAT');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Romania','ROM');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Russia','RUS');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Rwanda','RWA');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Saint Kitts and Nevis','SKN');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Saint Lucia','LCA');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Saint Vincent and the Grenadines','VIN');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Samoa','SAM');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('San Marino','SMR');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Sao Tome and Principe','STP');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Saudi Arabia','KSA');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Senegal','SEN');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Serbia','SCG');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Seychelles','SEY');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Sierra Leone','SLE');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Singapore','SIN');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Slovakia','SVK');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Slovenia','SLO');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Solomon Islands','SOL');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Somalia','SOM');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('South Africa','RSA');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Spain','ESP');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Sri Lanka','SRI');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Sudan','SUD');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Suriname','SUR');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Swaziland','SWZ');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Sweden','SWE');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Switzerland','SUI');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Syria','SYR');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Taiwan','TPE');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Tajikistan','TJK');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Tanzania','TAN');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Thailand','THA');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Togo','TOG');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Tonga','TGA');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Trinidad and Tobago','TRI');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Tunisia','TUN');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Turkey','TUR');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Turkmenistan','TKM');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Uganda','UGA');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Ukraine','UKR');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('United Arab Emirates','UAE');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('United Kingdom','GBR');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('United States','USA');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Uruguay','URU');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Uzbekistan','UZB');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Vanuatu','VAN');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Venezuela','VEN');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Vietnam','VIE');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Virgin Islands','ISV');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Yemen','YEM');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Zambia','ZAM');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Zimbabwe','ZIM');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('USSR','URS');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Czechoclovakia','TCH');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Australasia','ANZ');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Bohemia','BOH');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('British West Indies','BWI');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('United States','EUA');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('United States','SUA');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Unified Team','EUN');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('West Germany','FRG');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('East Germany','GDR');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Independent Olympians','IOP');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Independent Olympians','IOA');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('North Korea','NKO');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Romania','ROU');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Romania','RUM');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Russian Empire','RU1');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Serbia','SRB');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Yugoslavia','YUG');
Insert into olympics.COUNTRIES (NAME,COUNTRY_CODE) values ('Mulitple Nations','ZZX');