Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','48Kg','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','53Kg','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','58Kg','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','63Kg','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','69Kg','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','75Kg','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','- 47.6Kg (Light-Flyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','- 48Kg (Light-Flyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','- 52Kg (Flyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','- 54Kg (Bantamweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','- 55Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','- 56Kg (Bantamweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','- 60Kg (Featherweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','100 - 130Kg (Super Heavyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','47.6 - 52.16Kg (Flyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','48 - 52Kg (Flyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','48 - 54Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','52 - 57Kg (Bantamweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','52.16 - 56.7Kg (Bantamweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','54 - 58Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','54 - 60.3Kg (Featherweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','55 - 60Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','56 - 61Kg (Featherweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','56.7 - 61.23Kg (Featherweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','57 - 62Kg (Featherweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','57 - 63Kg (Featherweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','58 - 63Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','60 - 66Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','60 - 67.5Kg (Lightweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','60.3 - 66.6Kg (Lightweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','61 - 66Kg (Lightweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','61.23 - 65.77Kg (Lightweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','62 - 68Kg (Lightweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','63 - 67Kg (Lightweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','63 - 69Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','63 - 70Kg (Lightweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','65.77 - 71.67Kg (Welterweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','66 - 72Kg (Welterweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','66 - 74Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','66.6 - 73Kg (Middleweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','67 - 73Kg (Welterweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','67.5 - 75Kg (Middleweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','68 - 74Kg (Welterweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','69 - 76Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','70 - 78Kg (Welterweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','72 - 79Kg (Middleweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','73 - 79Kg (Middleweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','74 - 82Kg (Middleweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','74 - 84Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','75 - 80Kg (Light-Heavyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','76 - 85Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','78 - 87Kg (Middleweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','79 - 87Kg (Light-Heavyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','82 - 90Kg (Light-Heavyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','84 - 96Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','85 - 97Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','87 - 97Kg (Light-Heavyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','90 - 100Kg (Heavyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','96 - 120Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','97 - 130Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','- 48Kg','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','48 - 55Kg','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','55 - 63Kg','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Free.','63 - 72Kg','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','- 48Kg (Light-Flyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','- 52Kg (Flyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','- 55Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','- 56Kg (Bantamweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','- 58Kg (Bantamweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','- 60Kg (Featherweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','- 66.6Kg (Lightweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','100 - 130Kg (Super Heavyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','48 - 52Kg (Flyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','48 - 54Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','52 - 57Kg (Bantamweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','54 - 58Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','55 - 60Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','56 - 61Kg (Featherweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','57 - 61Kg (Featherweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','57 - 62Kg (Featherweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','57 - 63Kg (Featherweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','58 - 60Kg (Featherweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','58 - 62Kg (Featherweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','58 - 63Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','60 - 66Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','60 - 67.5Kg (Lightweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','61 - 66Kg (Lightweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','61 - 67Kg (Lightweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','62 - 67.5Kg (Lightweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','62 - 68Kg (Lightweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','63 - 69Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','63 - 70Kg (Lightweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','66 - 72Kg (Welterweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','66 - 74Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','66.6 - 73Kg (Middleweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','67 - 73Kg (Welterweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','67.5 - 75Kg (Middleweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','68 - 74Kg (Welterweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','69 - 76Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','70 - 78Kg (Welterweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','72 - 79Kg (Middleweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','73 - 79Kg (Middleweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','73 - 93Kg (Light-Heavyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','74 - 82Kg (Middleweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','74 - 84Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','75 - 82.5Kg (Light-Heavyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','75 - 82Kg (Light-Heavyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','76 - 85Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','78 - 87Kg (Middleweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','79 - 87Kg (Light-Heavyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','82 - 90Kg (Light-Heavyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','84 - 96Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','85 - 97Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','87 - 97Kg (Light-Heavyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','90 - 100Kg (Heavyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','96 - 120Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','97 - 130Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Wrestling Gre-R','Open Event','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Archery','Au Chapelet, 33M','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Archery','Au Chapelet, 50M','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Archery','Au Cordon Dorã©, 33M','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Archery','Au Cordon Dorã©, 50M','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Archery','Continental Style 50M','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Archery','Double American Round (60Y - 50Y - 40Y)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Archery','Double York Round (100Y - 80Y - 60Y)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Archery','Fixed Bird Target Large Birds','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Archery','Fixed Bird Target Large Birds Teams','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Archery','Fixed Bird Target Small Bird, Teams','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Archery','Fixed Bird Target Small Birds','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Archery','Individual (Fita Olympic Round - 70M)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Archery','Individual Fita Round','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Archery','Moving Bird Target 28M Teams','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Archery','Moving Bird Target 33M Teams','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Archery','Moving Bird Target 50M Teams','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Archery','Moving Bird Target, 28M','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Archery','Moving Bird Target, 33M','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Archery','Moving Bird Target, 50M','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Archery','Sur La Perche Ã La Herse','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Archery','Sur La Perche Ã La Pyramide','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Archery','Team (Fita Olympic Round - 70M)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Archery','Team Round 60Y','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Archery','Teams Fita Round','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Archery','York Round (100Y - 80Y - 60Y)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Archery','Double Columbia Round (50Y - 40Y - 30Y)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Archery','Double National Round (60Y - 50Y)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Archery','Individual (Fita Olympic Round - 70M)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Archery','Individual Fita Round','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Archery','National Round (60Y - 50Y)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Archery','Team (Fita Olympic Round - 70M)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Archery','Teams Fita Round','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Artistic G.','Club Swinging','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Artistic G.','Combined 3 Events','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Artistic G.','Combined 4 Events','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Artistic G.','Floor Exercises','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Artistic G.','Horizontal Bar','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Artistic G.','Indian Clubs','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Artistic G.','Individual All-Round','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Artistic G.','Parallel Bars','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Artistic G.','Pommel Horse','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Artistic G.','Rings','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Artistic G.','Rope Climbing','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Artistic G.','Sidehorse Vault','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Artistic G.','Team Competition','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Artistic G.','Team, Free System','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Artistic G.','Team, Horizontal Bar','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Artistic G.','Team, Parallel Bars','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Artistic G.','Team, Swedish System','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Artistic G.','Tumbling','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Artistic G.','Vault','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Artistic G.','Balance Beam','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Artistic G.','Floor Exercises','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Artistic G.','Individual All-Round','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Artistic G.','Team Competition','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Artistic G.','Team, Portable Apparatus','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Artistic G.','Uneven Bars','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Artistic G.','Vault','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','10000M','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','10000M Walk','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','100M','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','10Miles Walk (16093M)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','110M Hurdles','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','1500M','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','200M','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','200M Hurdles','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','20Km Walk','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','3000M Steeplechase','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','3000M Team','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','3000M Walk','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','3200M Steeplechase','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','3500M Walk','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','3Miles Team (4828M)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','4000M Steeplechase','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','400M','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','400M Hurdles','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','4Miles Team','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','4X100M Relay','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','4X400M Relay','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','5 Miles (8047M)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','5000M','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','5000M Team','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','50Km Walk','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','56Lb Weight Throw (25.4Kg)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','60M','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','800M','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','Cross Country Individual','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','Cross Country Team','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','Decathlon','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','Discus Throw','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','Discus Throw Ancient Style','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','Discus Throw, Both Hands','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','Hammer Throw','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','High Jump','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','High Jump, Standing','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','Javelin Throw','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','Javelin Throw Freestyle','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','Javelin Throw, Both Hands','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','Long Jump','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','Long Jump, Standing','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','Marathon','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','Pentathlon','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','Pole Vault','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','Shot Put','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','Shot Put, Both Hands','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','Triathlon (Long Jump / Shot Put / 100 Yards)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','Triple Jump','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','Triple Jump, Standing','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','10000M','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','10000M Walk','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','100M','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','100M Hurdles','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','1500M','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','200M','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','20Km Race Walk','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','3000M','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','3000M Steeplechase','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','400M','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','400M Hurdles','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','4X100M Relay','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','4X400M Relay','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','5000M','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','800M','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','80M Hurdles','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','Discus Throw','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','Hammer Throw','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','Heptathlon','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','High Jump','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','Javelin Throw','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','Long Jump','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','Marathon','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','Pentathlon','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','Pole Vault','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','Shot Put','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Athletics','Triple Jump','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Badminton','Doubles','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Badminton','Singles','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Badminton','Doubles','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Badminton','Singles','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Badminton','Doubles','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Baseball','Baseball','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Basketball','Basketball','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Basketball','Basketball','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Basque Pelota','Cesta Punta','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Beach volley.','Beach Volleyball','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Beach volley.','Beach Volleyball','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('BMX','Individual','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('BMX','Individual','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','- 47.63Kg (Flyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','- 48Kg (Light-Flyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','- 50.8Kg (Flyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','- 51Kg (Flyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','- 52.62Kg (Bantamweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','47.63 - 52.16Kg (Bantamweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','48 - 51Kg (Flyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','48Kg (Light Flywieght)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','50.8 - 53.52Kg (Bantamweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','50.8 - 54Kg (Bantamweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','51 - 54Kg (Bantamweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','52.16 - 56.7Kg (Featherweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','52.62 - 57.15Kg (Featherweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','53.52 - 57.15Kg (Featherweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','54 - 57.15Kg (Featherweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','54 - 57Kg (Featherweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','54 - 58Kg (Featherweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','56.7 - 61.24Kg (Lightweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','57 - 60Kg (Lightweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','57.15 - 61.24Kg (Lightweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','57.15 - 63.5Kg (Lightweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','58 - 62Kg (Lightweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','60 - 63.5Kg (Light-Welterweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','60 - 64 Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','61.24 - 65.77Kg (Welterweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','61.24 - 66.68Kg (Welterweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','62 - 67Kg (Welterweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','63.5 - 67Kg (Welterweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','63.5 - 71.67Kg (Middleweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','64 - 69 Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','65.77 - 71.67Kg (Middleweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','66.68 - 72.57Kg (Middleweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','67 - 71Kg (Light-Middleweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','67 - 73Kg (Middleweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','69 - 75 Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','71-75Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','72.57 - 79.38Kg (Light-Heavyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','73 - 80Kg (Light-Heavyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','75 - 81Kg (Light-Heavyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Boxing','81 - 91Kg (Heavyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Canoe / Kayak F','C-1 10000M','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Canoe / Kayak F','C-1 1000M (Canoe Single)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Canoe / Kayak F','C-1 500M (Canoe Single)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Canoe / Kayak F','C-2 10000M','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Canoe / Kayak F','C-2 1000M (Canoe Double)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Canoe / Kayak F','C-2 500M (Canoe Double)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Canoe / Kayak F','Folding K-1 10000M','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Canoe / Kayak F','Folding K-2 10000M','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Canoe / Kayak F','K-1 10000M','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Canoe / Kayak F','K-1 1000M (Kayak Single)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Canoe / Kayak F','K-1 4X500M','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Canoe / Kayak F','K-1 500M (Kayak Single)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Canoe / Kayak F','K-2 10000M','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Canoe / Kayak F','K-2 1000M (Kayak Double)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Canoe / Kayak F','K-2 500M (Kayak Double)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Canoe / Kayak F','K-4 1000M (Kayak Four)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Canoe / Kayak F','K-1 500M (Kayak Single)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Canoe / Kayak F','K-2 500M (Kayak Double)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Canoe / Kayak F','K-4 500M (Kayak Four)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Canoe / Kayak S','C-1 (Canoe Single)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Canoe / Kayak S','C-2 (Canoe Double)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Canoe / Kayak S','K-1 (Kayak Single)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Canoe / Kayak S','K-1 (Kayak Single)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cricket','Cricket','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Croquet','Double','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Croquet','Individual 1 Ball','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Croquet','Individual 2 Balls','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Road','Individual Road Race','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Road','Individual Time Trial','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Road','Team Time Trial','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Road','Individual Road Race','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Road','Individual Time Trial','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Track','1 Mile (1609.3M)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Track','1/2 Mile (804.7M)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Track','1/3 Mile (536.5M)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Track','1/4 Mile (402.3M)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Track','100Km','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Track','10Km','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Track','12-Hour Race','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Track','1980 Yards Pursuit, Team','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Track','1Km Pursuit','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Track','1Km Time Trial','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Track','2 Miles (3.218Km)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Track','2000M Tandem','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Track','20Km','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Track','25 Kilometres','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Track','25 Miles (40.232Km)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Track','5 Miles (8.046Km)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Track','5000M','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Track','50Km','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Track','Individual Pursuit','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Track','Keirin','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Track','Madison','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Track','Olympic Sprint','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Track','One Lap (660Y) Sprint','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Track','Points Race','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Track','Sprint Indivual','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Track','Team Pursuit (4000M)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Track','Team Sprint','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Track','500M Time Trial','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Track','Individual Pursuit','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Track','Points Race','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Cycling Track','Sprint','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Diving','10M Platform','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Diving','3M Springboard','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Diving','Plain High Diving','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Diving','Plunge For Distance','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Diving','Synchronized Diving 10M Platform','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Diving','Synchronized Diving 3M Springboard','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Diving','10M Platform','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Diving','3M Springboard','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Diving','Synchronized Diving 10M Platform','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Diving','Synchronized Diving 3M Springboard','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Dressage','Individual','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Dressage','Team','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Eventing','Individual','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Eventing','Team','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Fencing','Ã©Pã©E Individual','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Fencing','Ã©Pã©E Team','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Fencing','Ã©Pã©E, Amateurs And Masters','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Fencing','Ã©Pã©E, Masters','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Fencing','Foil Individual','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Fencing','Foil Team','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Fencing','Foil, Masters','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Fencing','Sabre Individual','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Fencing','Sabre Team','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Fencing','Sabre, Masters','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Fencing','Stick, Single','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Fencing','Ã©Pã©E Individual','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Fencing','Ã©Pã©E Team','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Fencing','Foil Individual','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Fencing','Foil Team','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Fencing','Sabre Individual','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Fencing','Sabre Team','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Figure skating','Individual','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Figure skating','Special Figures','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Figure skating','Individual','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Figure skating','Pairs','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Football','Football','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Football','Football','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Golf','Individual','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Golf','Team','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Golf','Individual','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Handball','Handball','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Handball','Handball','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Hockey','Hockey','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Hockey','Hockey','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Ice Hockey','Ice Hockey','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Jeu de Paume','Individual','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Judo','- 60 Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Judo','- 63Kg (Lightweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Judo','- 68Kg (Lightweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Judo','60 - 65Kg (Half-Lightweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Judo','60 - 66Kg (Half-Lightweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Judo','63 - 70Kg (Half-Middleweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Judo','65 - 71Kg (Lightweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Judo','66 - 73Kg (Lightweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Judo','68 - 80Kg (Middleweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Judo','70 - 80Kg (Middleweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Judo','71 - 78Kg (Half-Middleweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Judo','73 - 81Kg (Half-Middleweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Judo','78 - 86Kg (Middleweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Judo','80 - 93Kg (Half-Heavyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Judo','81 - 90Kg (Middleweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Judo','86 - 95Kg (Half-Heavyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Judo','90 - 100Kg (Half-Heavyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Judo','Open Category','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Judo','- 48 Kg','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Judo','- 48Kg (Extra-Lightweight)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Judo','48 - 52Kg (Half-Lightweight)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Judo','52 - 56Kg (Lightweight)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Judo','52 - 57Kg (Lightweight)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Judo','56 - 61Kg (Half-Middleweight)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Judo','57 - 63Kg (Half-Middleweight)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Judo','61 - 66Kg (Middleweight)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Judo','63 - 70Kg (Middleweight)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Judo','66 - 72Kg (Half-Heavyweight)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Judo','70 - 78Kg (Half-Heavyweight)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Jumping','High Jump','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Jumping','Individual','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Jumping','Long Jump Individual','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Jumping','Team','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Lacrosse','Lacrosse','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Modern Pentath.','Individual Competition','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Modern Pentath.','Team Competition','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Modern Pentath.','Individual Competition','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Mountain Bike','Cross-Country','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Mountain Bike','Cross-Country','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Polo','Polo','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Rackets','Double','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Rackets','Individual','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Rhythmic G.','Group Competition','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Rhythmic G.','Individual All-Round','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Roque','Individual','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Rowing','Coxed Fours Jugriggers','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Rowing','Coxless Pair (2-)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Rowing','Double Sculls (2X)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Rowing','Eight With Coxswain (8+)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Rowing','Four Without Coxswain (4-)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Rowing','Four-Oared Shell With Coxswain (4-)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Rowing','Lightweight Coxless Four (4-)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Rowing','Lightweight Double Sculls (2X)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Rowing','Pair-Oared Shell With Coxswain (2+)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Rowing','Quadruple Sculls Without Coxswain (4X)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Rowing','Single Sculls (1X)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Rowing','Coxless Four (4-)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Rowing','Double Sculls (2X)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Rowing','Eight With Coxswain (8+)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Rowing','Four-Oared Shell With Coxswain (4-)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Rowing','Lightweight Double Sculls (2X)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Rowing','Pair Without Coxswain (2-)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Rowing','Quadruple Sculls With Coxswain (4X)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Rowing','Quadruple Sculls Without Coxswain (4X)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Rowing','Single Sculls (1X)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Rugby','Rugby','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','470 - Two Person Dinghy','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','6M (Rating 1919)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','8M (Rating 1919)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','Board (Division Ii)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','Board (Lechner)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','Board (Mistral)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','Board (Windglider)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','Laser - One Person Dinghy','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','Rs:X - Windsurfer','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','Single-Handed Dinghy (Finn)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','Star - Keelboat','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','470 - Two Person Dinghy','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','Board (Lechner)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','Board (Mistral)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','Laser Radial - One Person Dinghy','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','Rs:X - Windsurfer','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','Single-Handed Dinghy (Europe)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','Yngling - Keelboat','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','0.5-1T','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','10-20T','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','10M','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','10M (Rating 1907)','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','10M (Rating 1919)','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','12 Foot Dinghy','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','12 Foot Dinghy Individual','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','12M','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','12M (Rating 1907)','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','12M (Rating 1919)','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','18 Foot Dinghy','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','30M Sq','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','3-10T','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','40M Sq','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','49Er - Skiff','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','5.5M','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','6.5M (Rating 1919)','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','6M','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','6M (Rating 1907)','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','7M','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','8M','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','8M (Rating 1907)','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','Dragon','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','Finn - Heavyweight Dinghy','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','Firefly Class','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','Fleet/Match Race Keelboat Open (Soling)','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','Flying Dutchman','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','Olympic Class Monotype','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','Open Class','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','Sharpie 12M2','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','Single-Handed Dinghy Open (Laser)','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','Swallow (Golondrina)','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','Tempest','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','Tornado - Multihull','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Sailing','Two-Person Keelboat Open (Star)','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','1000Y Free Rifle, Prone','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','100M Running Deer, Double Shots','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','100M Running Deer, Double Shots, Team','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','100M Running Deer, Single Shots','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','100M Running Deer, Single Shots, Team','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','100M Running Deer, Single/Double Shots','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','10M Air Pistol (60 Shots)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','10M Air Rifle (60 Shots)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','10M Running Target (30+30 Shots)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','25M Army Pistol','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','25M Rapid Fire Pistol (60 Shots)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','25M Small Bore Rifle, Team','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','25M Small Rifle','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','25Y Small Bore Rifle, Disappearing Target','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','25Y Small Bore Rifle, Moving Target','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','300+600M Free Rifle, Team, Prone','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','300M Free Rifle 3 Positions (3X40 Shots)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','300M Free Rifle, Prone, Team','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','300M Free Rifle, Standing, Team','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','30M Army Pistol, Team','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','400, 600, 800M Free Rifle, Team','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','50+100Y Small Bore Rifle, Team','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','50M Army Pistol, Team','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','50M Pistol (60 Shots)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','50M Rifle 3 Positions (3X40 Shots)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','50M Rifle Prone (60 Shots)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','50M Running Target (30+30 Shots)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','50M Small Bore Rifle, Standing, Individual','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','50M Small Bore Rifle, Team','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','50Y Army Pistol, Team','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','600M Free Rifle','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','600M Free Rifle, Individual','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','600M Free Rifle, Prone','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','600M Free Rifle, Team','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','Army Rifle, 200M','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','Army Rifle, 300M','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','Army Rifle, 300M, 3 Positions','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','Army Rifle, 300M, Kneeling','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','Army Rifle, 300M, Prone','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','Army Rifle, 300M, Standing','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','Clay Pigeons, Team','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','Double Trap (150 Targets)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','Free Rifle, Team','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','Rifle, Team','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','Skeet (125 Targets)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','Trap (125 Targets)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','10M Air Pistol (40 Shots)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','10M Air Rifle (40 Shots)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','25M Pistol (30+30 Shots)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','50M Rifle 3 Positions (3X20 Shots)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','Double Trap (120 Targets)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','Skeet (75 Targets)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','Trap (75 Targets)','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','25M Rapid Fire Pistol (60 Shots)','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','300M Free Rifle 3 Positions (3X40 Shots)','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','50M Pistol (60 Shots)','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','50M Rifle 3 Positions (3X40 Shots)','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','50M Rifle Prone (60 Shots)','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','50M Running Target (30+30 Shots)','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','Skeet (125 Targets)','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Shooting','Trap (125 Targets)','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Softball','Softball','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','100M Backstroke','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','100M Breaststroke','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','100M Butterfly','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','100M Freestyle','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','100M Freestyle For Sailors','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','1200M Freestyle','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','1500M Freestyle','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','200M Backstroke','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','200M Breaststroke','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','200M Butterfly','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','200M Freestyle','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','200M Individual Medley','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','200M Obstacle Event','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','200M Team Swimming','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','4000M Freestyle','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','400M Breaststroke','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','400M Freestyle','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','400M Individual Medley','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','4X100M Freestyle Relay','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','4X100M Medley Relay','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','4X200M Freestyle Relay','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','4X50Y Freestyle Relay','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','50M Freestyle','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','50Y Freestyle (45.72M)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','880Y Freestyle (804.66M)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','Marathon 10Km','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','Underwater Swimming','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','100M Backstroke','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','100M Breaststroke','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','100M Butterfly','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','100M Freestyle','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','200M Backstroke','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','200M Breaststroke','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','200M Butterfly','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','200M Freestyle','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','200M Individual Medley','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','400M Freestyle','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','400M Individual Medley','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','4X100M Freestyle Relay','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','4X100M Medley Relay','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','4X200M Freestyle Relay','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','50M Freestyle','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','800M Freestyle','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Swimming','Marathon 10Km','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Synchronized S.','Duet','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Synchronized S.','Solo','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Synchronized S.','Team','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Table Tennis','Doubles','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Table Tennis','Singles','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Table Tennis','Team','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Table Tennis','Doubles','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Table Tennis','Singles','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Table Tennis','Team','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Taekwondo','- 58 Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Taekwondo','58 - 68 Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Taekwondo','68 - 80 Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Taekwondo','- 49 Kg','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Taekwondo','49 - 57 Kg','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Taekwondo','57 - 67 Kg','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Tennis','Doubles','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Tennis','Doubles Indoor','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Tennis','Singles','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Tennis','Singles Indoor','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Tennis','Doubles','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Tennis','Singles','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Tennis','Singles Indoor','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Tennis','Mixed Doubles','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Tennis','Mixed Doubles Indoor','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Trampoline','Individual','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Trampoline','Individual','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Triathlon','Individual','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Triathlon','Individual','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Tug of War','Tug Of War','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Vaulting','Figure Riding Individual','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Vaulting','Figure Riding Team','X');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Volleyball','Volleyball','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Volleyball','Volleyball','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Water Motorspor','8M Class C','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Water Motorspor','Class B Up To 60 Feet','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Water Motorspor','Open Class A','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Water polo','Water Polo','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Water polo','Water Polo','W');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','- 52Kg, Total (Flyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','- 54Kg, Total (Flyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','- 56Kg, Total (Bantamweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','- 60Kg, One-Two Hand 3 Events (Featherweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','- 60Kg, One-Two Hand 5 Events (Featherweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','- 60Kg, Total (Featherweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','100 - 110Kg, Total (Heavyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','105Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','52 - 56Kg, Total (Bantamweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','54 - 59Kg, Total (Bantamweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','56 - 60Kg, Total (Featherweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','56Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','59 - 64Kg, Total (Featherweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','60 - 67.5Kg, One-Two Hand 3 Events (Lightweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','60 - 67.5Kg, One-Two Hand 5 Events (Lightweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','60 - 67.5Kg, Total (Lightweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','62Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','64 - 70Kg, Total (Lightweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','67.5 - 75Kg, One-Two Hand 3 Events (Middleweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','67.5 - 75Kg, One-Two Hand 5 Events (Middleweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','67.5 - 75Kg, Total (Middleweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','69Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','70 - 76Kg, Total (Middleweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','75 - 82.5Kg, One-Two Hand 3 E. (Light-Heavyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','75 - 82.5Kg, One-Two Hand 5 E. (Light-Heavyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','75 - 82.5Kg, Total (Light-Heavyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','76 - 83Kg, Total (Light-Heavyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','77Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','82.5 - 90Kg, Total (Middle-Heavyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','83 - 91Kg, Total (Middle-Heavyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','85Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','90 - 100Kg, Total (First-Heavyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','91 - 110Kg, Total (Heavyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','91 - 99Kg, Total (First-Heavyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','94Kg','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','99 - 108Kg, Total (Heavyweight)','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','All-Around Dumbbell Contest','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','Heavyweight - One Hand Lift','M');
Insert into olympics.EVENT (DISCIPLINE,EVENT_NAME,EVENT_GENDER) values ('Weightlifting','Heavyweight - Two Hand Lift','M');