--------------------------------------------------------
--  File created - Saturday-December-03-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEDALS2
--------------------------------------------------------

  CREATE TABLE "ABHINAV21793"."MEDALS2" 
   (	"YEAR" NUMBER(6,0), 
	"GENDER" VARCHAR2(2 BYTE), 
	"NUM_GOLD" NUMBER(5,0), 
	"NUM_SILVER" NUMBER(5,0), 
	"NUM_BRONZE" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MEDALS2
--------------------------------------------------------

  ALTER TABLE "ABHINAV21793"."MEDALS2" MODIFY ("NUM_BRONZE" NOT NULL ENABLE);
  ALTER TABLE "ABHINAV21793"."MEDALS2" MODIFY ("NUM_SILVER" NOT NULL ENABLE);
  ALTER TABLE "ABHINAV21793"."MEDALS2" MODIFY ("NUM_GOLD" NOT NULL ENABLE);
  ALTER TABLE "ABHINAV21793"."MEDALS2" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "ABHINAV21793"."MEDALS2" MODIFY ("YEAR" NOT NULL ENABLE);
