Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Aquatics','Swimming');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Aquatics','Water polo');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Aquatics','Diving');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Aquatics','Synchronized S.');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Archery','Archery');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Athletics','Athletics');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Badminton','Badminton');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Baseball','Baseball');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Basketball','Basketball');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Basque Pelota','Basque Pelota');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Boxing','Boxing');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Canoe / Kayak','Canoe / Kayak F');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Canoe / Kayak','Canoe / Kayak S');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Cricket','Cricket');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Croquet','Croquet');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Cycling','Cycling Road');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Cycling','Cycling Track');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Cycling','Mountain Bike');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Cycling','BMX');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Equestrian','Jumping');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Equestrian','Dressage');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Equestrian','Eventing');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Equestrian','Vaulting');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Fencing','Fencing');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Football','Football');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Golf','Golf');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Gymnastics','Artistic G.');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Gymnastics','Rhythmic G.');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Gymnastics','Trampoline');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Handball','Handball');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Hockey','Hockey');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Ice Hockey','Ice Hockey');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Jeu de paume','Jeu de Paume');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Judo','Judo');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Lacrosse','Lacrosse');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Modern Pentathlon','Modern Pentath.');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Polo','Polo');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Rackets','Rackets');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Roque','Roque');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Rowing','Rowing');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Rugby','Rugby');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Sailing','Sailing');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Shooting','Shooting');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Skating','Figure skating');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Softball','Softball');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Table Tennis','Table Tennis');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Taekwondo','Taekwondo');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Tennis','Tennis');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Triathlon','Triathlon');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Tug of War','Tug of War');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Volleyball','Volleyball');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Volleyball','Beach volley.');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Water Motorsports','Water Motorspor');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Weightlifting','Weightlifting');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Wrestling','Wrestling Gre-R');
Insert into olympics.SPORTS_INFO (SPORT,DISCIPLINE) values ('Wrestling','Wrestling Free.');