--------------------------------------------------------
--  File created - Saturday-December-03-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WON
--------------------------------------------------------

  CREATE TABLE "ABHINAV21793"."WON" 
   (	"YEAR" NUMBER(6,0), 
	"AID" NUMBER(5,0), 
	"DISCIPLINE" VARCHAR2(128 BYTE), 
	"EVENT_NAME" VARCHAR2(128 BYTE), 
	"EVENT_GENDER" VARCHAR2(2 BYTE), 
	"MEDAL" VARCHAR2(26 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table WON
--------------------------------------------------------

  ALTER TABLE "ABHINAV21793"."WON" MODIFY ("EVENT_GENDER" NOT NULL ENABLE);
  ALTER TABLE "ABHINAV21793"."WON" MODIFY ("EVENT_NAME" NOT NULL ENABLE);
  ALTER TABLE "ABHINAV21793"."WON" MODIFY ("DISCIPLINE" NOT NULL ENABLE);
  ALTER TABLE "ABHINAV21793"."WON" MODIFY ("AID" NOT NULL ENABLE);
  ALTER TABLE "ABHINAV21793"."WON" MODIFY ("YEAR" NOT NULL ENABLE);
