Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (1204,'Bruce Robert','Baumgartner','Wrestling Free.');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (1234,'Charles','Beachcroft','Cricket');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (2226,'Patrick','Brennan','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (2228,'W.','Brennaugh','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (2597,'Wally','Byron','Ice Hockey');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (4445,'Charles Percy','Dixon','Tennis');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (4515,'Reginald Frank','Doherty','Tennis');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (4630,'Burton','Downing','Cycling Track');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (7283,'Tanya','Harding','Softball');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (8481,'Benjamin','Jamieson','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (8798,'William Athelstan','Johnson','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (12372,'Joseph','Mccormick','Ice Hockey');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (14683,'Jan','Peka','Ice Hockey');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (18670,'Istvan','Szivos','Water polo');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (18799,'Ryoko','Tani','Judo');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (19163,'Charles Lee','Tilden','Rugby');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (19533,'Alexander T.','Turnbull','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (19827,'Anky','Van Grunsven','Dressage');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (20253,'Gennadi','Volnov','Basketball');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (20505,'Natalie','Ward','Softball');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (20163,'Otto','Vindys','Ice Hockey');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (14946,'Paola','Pezzo','Mountain Bike');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (14961,'Michael','Phelps','Swimming');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (16076,'Melanie','Roche','Softball');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (16461,'Inna','Ryskal','Volleyball');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (16708,'Ricardo','Santos','Beach volley.');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (14371,'Charles Ferdinand','Pahud De Mortanges','Eventing');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (14555,'George','Passmore','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (2107,'Alfred James','Bowerman','Cricket');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (2057,'T.','Bouckaert','Vaulting');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (2086,'Adolphe René','Bousquet','Rugby');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (1562,'Anna','Bessonova','Rhythmic G.');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (3448,'Anthony','Conroy','Ice Hockey');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (4497,'Bevan','Docherty','Triathlon');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (4625,'J.W.','Dowling','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (5522,'Edward','Fitzgerald','Ice Hockey');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (5564,'Jack','Flett','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (5887,'J.','Fyon','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (7344,'Karel','Hartmann','Ice Hockey');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (8443,'Charles','Jacobus','Roque');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (7794,'Pavol','Hochschorner','Canoe / Kayak S');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (8102,'Frederick Harkness','Humphreys','Tug of War');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (8119,'Joseph Garvin','Hunter','Rugby');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (18968,'Henry John','Terry','Cricket');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (19221,'Mark','Todd','Eventing');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (20482,'Nan','Wang','Table Tennis');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (15002,'Zbigniew','Pietrzykowski','Boxing');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (15187,'Imre','Polyak','Wrestling Gre-R');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (16545,'Oleg','Saitov','Boxing');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (14450,'Laszlo','Papp','Boxing');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (735,'W.T.','Attrill','Cricket');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (1670,'Arthur Ernest','Birkett','Cricket');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (3360,'Karen','Cockburn','Trampoline');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (4402,'Pyrros','Dimas','Weightlifting');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (4504,'Charles Webster','Doe','Rugby');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (4561,'William Stephen','Donne','Cricket');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (6438,'Frank Xavier','Goheen','Ice Hockey');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (6587,'Jay','Gould','Jeu de Paume');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (7956,'R.','Horne','Cricket');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (8828,'Edward Percy','Jones','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (9468,'Dong Moon','Kim','Badminton');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (10830,'Pavel','Lednev','Modern Pentath.');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (11262,'Elisabeta','Lipa','Rowing');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (11881,'Ragnar','Malm','Cycling Road');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (20697,'Isabell','Werth','Dressage');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (21006,'John','Wodehouse','Polo');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (17279,'Gunnar','Setterwall','Tennis');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (20161,'Francisco','Villota Baquiola','Basque Pelota');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (13629,'Francis Clement','Newton','Golf');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (17624,'Udham','Singh Kullar','Hockey');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (15617,'H.W.','Ramsey','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (18254,'Teofilo','Stevenson','Boxing');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (1466,'Laura','Berg','Softball');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (1740,'Elie','Blanchard','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (3968,'José','De Amezola Y Aspizua','Basque Pelota');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (4425,'Piero','D''Inzeo','Jumping');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (4426,'Raimondo','D''Inzeo','Jumping');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (4684,'Herbert','Drury','Ice Hockey');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (4707,'Richard Louis','Duckett','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (5788,'Christian','Fridfinnson','Ice Hockey');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (7420,'S.N.','Hayes','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (7232,'Henry Peter Christian','Hansen','Cycling Road');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (8786,'Phyllis','Johnson','Figure skating');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (10785,'Pedro Luis','Lazo','Baseball');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (10790,'Laetitia','Le Corguille','BMX');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (10718,'Larisa','Latynina','Artistic G.');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (12401,'A.','Mcevoy','Cricket');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (11924,'Edoardo','Mangiarotti','Fencing');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (20608,'Cyril','Weidenborner','Ice Hockey');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (18612,'John','Symes','Cricket');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (19257,'P.H.','Tomalin','Cricket');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (19904,'Arnold','Vanderlijde','Boxing');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (16647,'Arantxa','Sanchez-Vicario','Tennis');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (14222,'William F.L.','Orris','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (16881,'Norbert','Schemansky','Weightlifting');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (18184,'Kerstin','Stegemann','Football');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (14584,'Ivan','Patzaichin','Canoe / Kayak F');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (415,'W.','Anderson','Cricket');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (717,'John Jacob','Astor','Rackets');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (1778,'L.','Blockey','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (2155,'J.','Braid','Cricket');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (2283,'John','Broderick','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (2332,'Charles','Brown','Roque');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (2360,'W.','Browning','Cricket');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (3721,'Frederick Wlliam','Cuming','Cricket');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (6203,'George Pierce','Geran','Ice Hockey');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (7085,'Haldor','Halderson','Ice Hockey');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (7926,'Henry Frank','Hoobin','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (8123,'Robert Edward','Hunter','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (10516,'Boris','Lagutin','Boxing');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (10524,'Hilliard','Laidlaw','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (11646,'H.','Lyle','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (12448,'Burt P.','Mckinnie','Golf');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (12835,'Edwin Archer','Mills','Tug of War');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (19110,'Thomas','Thornycroft','Water Motorspor');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (13922,'Paavo','Nurmi','Athletics');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (17726,'Colby Edward','Slater','Rugby');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (16791,'Dmitry','Sautin','Diving');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (14508,'J.','Parker-Smith','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (15736,'Bernard','Redwood','Water Motorspor');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (16983,'A.J.','Schneidau','Cricket');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (2432,'Gerald Frederick','Buckland','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (3339,'George','Cloutier','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (8871,'T.H.','Jordan','Cricket');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (9530,'Soo-Nyung','Kim','Archery');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (9590,'Jill','Kintner','BMX');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (11244,'Renate','Lingor','Football');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (11986,'A.','Mara','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (12193,'G.','Mason','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (12194,'G.J.','Mason','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (12464,'D.','Mcleod','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (12525,'Charles Thomas','Mehan','Rugby');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (20772,'Simon','Whitfield','Triathlon');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (18377,'Smith O.','Streeter','Roque');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (18605,'Florence','Syers','Figure skating');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (18734,'Miho','Takeda','Synchronized S.');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (19250,'Montagu Henry','Toller','Cricket');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (14933,'Gösta A.B.','Pettersson','Cycling Road');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (14042,'Seongok','Oh','Handball');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (15307,'Alfred James','Powlesland','Cricket');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (17008,'Rudolph John','Scholz','Rugby');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (14572,'John Clarence','Patrick','Rugby');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (1380,'Sergei','Belov','Basketball');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (2536,'William Laurie','Burns','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (2688,'George H.','Campbell','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (2883,'George','Cattanach','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (3522,'Harry Richard','Corner','Cricket');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (3966,'Mike','Day','BMX');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (4448,'Frank J.','Dixon','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (5381,'Ana Ibis','Fernandez','Volleyball');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (6524,'Michael','Goodman','Ice Hockey');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (6558,'Thomas Patrick','Gorman','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (6623,'Torben','Grael','Sailing');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (7756,'Ariane','Hingst','Football');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (8768,'F.S.','Johnson','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (9073,'Hamit','Kaplan','Wrestling');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (10801,'Henry Meredith','Leaf','Rackets');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (11657,'Neville Stephen','Lytton','Jeu de Paume');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (12374,'Lawrence','Mccormick','Ice Hockey');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (13287,'William','Muldoon','Rugby');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (20773,'Normnan Henry Pownall','Whitley','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (20826,'Bradley','Wiggins','Cycling Track');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (17127,'Charles Hubert','Scott','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (18397,'Maris','Strombergs','BMX');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (18694,'Miya','Tachibana','Synchronized S.');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (17433,'H.','Shorrocks','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (13801,'Evan Baille','Noel','Rackets');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (16513,'Hadi','Saei','Taekwondo');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (14171,'John T.','O''Neil','Rugby');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (14245,'Carl Townsend','Osburn','Shooting');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (18043,'Sabine','Spitz','Mountain Bike');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (14411,'Jan','Palous','Ice Hockey');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (69,'Julien','Absalon','Mountain Bike');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (1439,'Robert','Benson','Ice Hockey');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (1077,'Frederick Whitfield','Barrett','Polo');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (3196,'Frederick William','Christian','Cricket');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (3315,'Leslie Walter','Claudius','Hockey');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (2433,'George John','Buckley','Cricket');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (2493,'Francis Romulus','Burchell','Cricket');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (7795,'Peter','Hochschorner','Canoe / Kayak S');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (10759,'Natalia','Lavrova','Rhythmic G.');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (12439,'Clarence D.','Mckerrow','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (12794,'Eustace Hamilton','Miles','Jeu de Paume');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (21622,'Leontien','Zijlaard-Van Moorsel','Cycling Road');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (21071,'Allan','Woodman','Ice Hockey');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (17145,'Briana','Scurry','Football');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (14828,'Karel','Pesek','Ice Hockey');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (18615,'Francis Allen','Synnott','Ice Hockey');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (20031,'A.H.','Venn','Lacrosse');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (17367,'James','Shepherd','Tug of War');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (13877,'Dezsö','Novak','Football');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (15257,'Elena','Posevina','Rhythmic G.');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (15365,'Birgit','Prinz','Football');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (18068,'Josef','Sroubek','Ice Hockey');
Insert into olympics.QUES4 (AID,FNAME,LNAME,SPORT) values (14520,'Cindy','Parlow','Football');
