Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (928,'Andras','Balczo','Modern Pentath.');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (29,'Margaret Ives','Abbott','Golf');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (2113,'Shannon','Boxx','Football');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (2226,'Patrick','Brennan','Lacrosse');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (2228,'W.','Brennaugh','Lacrosse');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (2597,'Wally','Byron','Ice Hockey');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (1204,'Bruce Robert','Baumgartner','Wrestling Free.');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (1234,'Charles','Beachcroft','Cricket');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (1359,'Regla Maritza','Bell','Volleyball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (4510,'Anna','Dogonadze','Trampoline');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (4515,'Reginald Frank','Doherty','Tennis');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (8391,'Lilia','Izquierdo','Volleyball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (8463,'Walter','Jakobsson','Figure skating');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (8481,'Benjamin','Jamieson','Lacrosse');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (7434,'Wenna','He','Trampoline');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (8126,'Marcus','Hurley','Cycling Track');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (9241,'Foxhall Parker','Keene','Polo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (9735,'Reiner','Klimke','Dressage');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (9561,'Orestes','Kindelan','Baseball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (11825,'Tatiana','Makarets-Kochergina','Handball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (14371,'Charles Ferdinand','Pahud De Mortanges','Eventing');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (14429,'Nikolay','Panin','Figure skating');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (14462,'Eduardo','Paret','Baseball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (13201,'Alexander','Moskalenko','Trampoline');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (13503,'Guillermo','Naylor','Polo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (14946,'Paola','Pezzo','Mountain Bike');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (14961,'Michael','Phelps','Swimming');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (16572,'Ulrich','Salchow','Figure skating');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (18651,'Zoltan','Szecsi','Water polo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (18670,'Istvan','Szivos','Water polo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (18929,'Levan','Tediashvili','Wrestling Free.');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (19163,'Charles Lee','Tilden','Rugby');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (19324,'Regla','Torres','Volleyball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (19533,'Alexander T.','Turnbull','Lacrosse');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (21531,'Ning','Zhang','Badminton');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (383,'Camilla','Andersen','Handball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (393,'Kristine','Andersen','Handball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (2107,'Alfred James','Bowerman','Cricket');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (1462,'Liubov','Berezhnaya-Odinokova','Handball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (2057,'T.','Bouckaert','Vaulting');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (3727,'Edward M.','Cummins','Golf');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (5564,'Jack','Flett','Lacrosse');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (4722,'Luis J.','Duggan','Polo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (6211,'Aladar','Gerevich','Fencing');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (6629,'Gillis','Grafstr„ñM','Figure skating');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (5887,'J.','Fyon','Lacrosse');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (8443,'Charles','Jacobus','Roque');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (7794,'Pavol','Hochschorner','Canoe / Kayak S');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (8064,'Angela','Hucles','Football');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (8102,'Frederick Harkness','Humphreys','Tug of War');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (8119,'Joseph Garvin','Hunter','Rugby');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (10756,'Andrey','Lavrov','Handball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (12055,'Kate','Markgraf','Football');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (12814,'Charles Darley','Miller','Polo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (14450,'Laszlo','Papp','Boxing');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (13370,'Halil','Mutlu','Weightlifting');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (13943,'Heather','O Reilly','Football');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (15636,'Lene','Rantala','Handball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (15700,'Alfred','Rawlinson','Polo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (15734,'Steven','Redgrave','Rowing');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (19941,'Lazaro','Vargas','Baseball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (20362,'Aly','Wagner','Football');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (20369,'Katrin','Wagner-Augustin','Canoe / Kayak F');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (18856,'Lindsay','Tarpley','Football');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (18914,'Artur','Taymazov','Wrestling Free.');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (20719,'Carl','Westergren','Wrestling Gre-R');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (20862,'George','Wilkinson','Water polo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (20942,'Herbert Haydon','Wilson','Polo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (21551,'Yining','Zhang','Table Tennis');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (20482,'Nan','Wang','Table Tennis');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (1670,'Arthur Ernest','Birkett','Cricket');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (1803,'Liudmila','Bobrus-Paradnik','Handball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (2052,'Tina','Bottzau','Handball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (3551,'Marlenis','Costa','Volleyball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (4402,'Pyrros','Dimas','Weightlifting');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (4504,'Charles Webster','Doe','Rugby');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (4561,'William Stephen','Donne','Cricket');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (7260,'Anna','H„úbler','Figure skating');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (6587,'Jay','Gould','Jeu de Paume');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (6129,'Andres','Gazzotti','Polo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (9468,'Dong Moon','Kim','Badminton');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (11262,'Elisabeta','Lipa','Rowing');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (11034,'Carl','Lewis','Athletics');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (12469,'Brigitte','Mcmahon','Triathlon');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (12513,'Aleksandr','Medved','Wrestling Free.');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (14355,'Juan','Padilla','Baseball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (13715,'Yuri','Nikitin','Trampoline');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (17794,'Charles Sydney','Smith','Water polo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (18254,'Teofilo','Stevenson','Boxing');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (18595,'Sheryl','Swoopes','Basketball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (17624,'Udham','Singh Kullar','Hockey');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (20161,'Francisco','Villota Baquiola','Basque Pelota');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (20697,'Isabell','Werth','Dressage');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (21527,'Jun','Zhang','Badminton');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (21006,'John','Wodehouse','Polo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (21264,'Ivan','Yarygin','Wrestling Free.');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (1300,'Ludger','Beerbaum','Jumping');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (1466,'Laura','Berg','Softball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (1525,'Arthur','Berry','Football');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (1740,'Elie','Blanchard','Lacrosse');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (3102,'Aldona','Chesaitite-Nenenene','Handball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (3968,'Jos√©','De Amezola Y Aspizua','Basque Pelota');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (5370,'Ian Gordon','Ferguson','Canoe / Kayak F');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (5788,'Christian','Fridfinnson','Ice Hockey');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (5808,'Jan','Frodeno','Triathlon');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (4244,'Yaping','Deng','Table Tennis');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (4707,'Richard Louis','Duckett','Lacrosse');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (6825,'Jun','Gu','Badminton');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (6921,'Jingjing','Guo','Diving');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (8020,'Chris','Hoy','Cycling Track');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (9425,'Lotte','Kiaerskou','Handball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (9115,'Larisa','Karlova','Handball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (11481,'Gregory','Louganis','Diving');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (10718,'Larisa','Latynina','Artistic G.');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (10785,'Pedro Luis','Lazo','Baseball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (12245,'Valter','Matosevic','Handball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (12819,'George Arthur','Miller','Polo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (12530,'George Nicholas','Mehnert','Wrestling Free.');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (12580,'Teignmouth Philip','Melville','Polo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (14222,'William F.L.','Orris','Lacrosse');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (14345,'Antonio','Pacheco','Baseball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (13652,'Patteson Wormesley','Nickalls','Polo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (15539,'Paul','Radmilovic','Water polo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (14584,'Ivan','Patzaichin','Canoe / Kayak F');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (16677,'Charles Edward','Sands','Golf');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (18612,'John','Symes','Cricket');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (18099,'Dawn','Staley','Basketball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (17620,'Randhir','Singh Gentle','Hockey');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (20101,'Mette','Vestergaard Larsen','Handball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (20912,'Venus','Williams','Tennis');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (20973,'Hans G√ºnter','Winkler','Jumping');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (21058,'Warren K.','Wood','Golf');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (176,'Omar','Ajete','Baseball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (717,'John Jacob','Astor','Rackets');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (2283,'John','Broderick','Lacrosse');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (3069,'Zhong','Chen','Taekwondo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (3721,'Frederick Wlliam','Cuming','Cricket');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (3953,'Anastasia','Davydova','Synchronized S.');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (2821,'Hamish','Carter','Triathlon');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (5513,'Morris','Fisher','Shooting');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (6980,'Dezso','Gyarmati','Water polo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (7085,'Haldor','Halderson','Ice Hockey');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (8461,'Ludowika','Jakobsson','Figure skating');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (7926,'Henry Frank','Hoobin','Lacrosse');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (8122,'Robert Edward','Hunter','Golf');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (8190,'Kaori','Icho','Wrestling Free.');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (9317,'Arturo','Kenny','Polo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (9483,'Il','Kim','Wrestling Free.');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (9649,'Gergely','Kiss','Water polo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (11646,'H.','Lyle','Lacrosse');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (10524,'Hilliard','Laidlaw','Lacrosse');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (10581,'Alfred P.','Lane','Shooting');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (12835,'Edwin Archer','Mills','Tug of War');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (13552,'Juan','Nelson','Polo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (13922,'Paavo','Nurmi','Athletics');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (15613,'Christie','Rampone','Football');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (15736,'Bernard','Redwood','Water Motorspor');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (17811,'John','Smith','Wrestling Free.');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (17854,'Clement E.','Smoot','Golf');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (17726,'Colby Edward','Slater','Rugby');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (19110,'Thomas','Thornycroft','Water Motorspor');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (19523,'Zinaida','Turchina','Handball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (21323,'Saori','Yoshida','Wrestling Free.');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (1163,'Mavlet','Batirov','Wrestling Free.');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (2907,'Pedro','Cea','Football');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (3793,'Mustafa','Dagistanli','Wrestling Free.');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (3339,'George','Cloutier','Lacrosse');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (5391,'Lisa','Fernandez','Softball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (5837,'Mingxia','Fu','Diving');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (7314,'Lori','Harrigan','Softball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (6130,'Fei','Ge','Badminton');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (7634,'Alberto','Hernandez','Baseball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (9895,'Janne','Kolling','Handball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (9530,'Soo-Nyung','Kim','Archery');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (9675,'Tonje','Kjaergaard','Handball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (9101,'Irina','Karavaeva','Trampoline');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (9156,'Tamas','Kasas','Water polo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (11365,'Vivian Noverre','Lockett','Polo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (11559,'Alejandrina','Luis','Volleyball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (11650,'George Seymour','Lyon','Golf');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (11726,'Frank Jay','Mackey','Polo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (11986,'A.','Mara','Lacrosse');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (12181,'Javier','Mascherano','Football');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (13015,'Tamas','Molnar','Water polo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (12464,'D.','Mcleod','Lacrosse');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (12525,'Charles Thomas','Mehan','Rugby');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (14354,'Enrique','Padilla','Polo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (13815,'Tadahiro','Nomura','Judo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (14960,'Mason Elliot','Phelps','Golf');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (15307,'Alfred James','Powlesland','Cricket');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (14572,'John Clarence','Patrick','Rugby');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (17008,'Rudolph John','Scholz','Rugby');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (18471,'Naim','Suleymanoglu','Weightlifting');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (18605,'Florence','Syers','Figure skating');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (19250,'Montagu Henry','Toller','Cricket');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (19588,'Yojiro','Uetake','Wrestling Free.');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (20772,'Simon','Whitfield','Triathlon');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (167,'Ben','Ainslie','Sailing');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (601,'Pedro','Arispe','Football');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (2536,'William Laurie','Burns','Lacrosse');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (1373,'Sergei','Beloglazov','Wrestling Free.');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (1401,'Tibor','Benedek','Water polo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (1674,'Peter','Biros','Water polo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (2883,'George','Cattanach','Lacrosse');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (3821,'Dennis','Daly','Polo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (3522,'Harry Richard','Corner','Cricket');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (2688,'George H.','Campbell','Lacrosse');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (5381,'Ana Ibis','Fernandez','Volleyball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (4448,'Frank J.','Dixon','Lacrosse');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (6524,'Michael','Goodman','Ice Hockey');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (6558,'Thomas Patrick','Gorman','Lacrosse');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (7817,'Anette','Hoffman','Handball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (9130,'Gy√∂rgy','Karpati','Water polo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (11517,'Chunlong','Lu','Trampoline');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (13086,'Nathaniel Fish','Moore','Golf');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (12375,'Patricia','Mccormick','Diving');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (14171,'John T.','O''Neil','Rugby');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (14245,'Carl Townsend','Osburn','Shooting');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (13287,'William','Muldoon','Rugby');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (13801,'Evan Baille','Noel','Rackets');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (15011,'Kustaa','Pihlajam„ÑKi','Wrestling Free.');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (15928,'Johan','Rickttoff','Wrestling');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (17141,'Antonio','Scull','Baseball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (16513,'Hadi','Saei','Taekwondo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (17871,'Emma','Snowsill','Triathlon');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (18397,'Maris','Strombergs','BMX');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (17617,'Balbir','Singh Dosanjh','Hockey');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (19601,'Luis','Ulacia','Baseball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (20437,'Kerri','Walsh','Beach volley.');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (1077,'Frederick Whitfield','Barrett','Polo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (69,'Julien','Absalon','Mountain Bike');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (2433,'George John','Buckley','Cricket');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (2493,'Francis Romulus','Burchell','Cricket');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (2505,'Heinrich','Burger','Figure skating');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (1439,'Robert','Benson','Ice Hockey');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (3196,'Frederick William','Christian','Cricket');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (3315,'Leslie Walter','Claudius','Hockey');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (5827,'Katrine','Fruelund','Handball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (6469,'Slavko','Goluza','Handball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (6097,'Idalmis','Gato','Volleyball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (7400,'Rechelle','Hawkes','Hockey');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (7795,'Peter','Hochschorner','Canoe / Kayak S');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (11467,'Venio','Losert','Handball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (10759,'Natalia','Lavrova','Rhythmic G.');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (10888,'Willis','Lee','Shooting');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (12797,'Juan','Miles','Polo');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (12937,'Heather','Mitts','Football');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (12439,'Clarence D.','Mckerrow','Lacrosse');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (11930,'Valentyn','Mankin','Sailing');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (14520,'Cindy','Parlow','Football');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (13160,'Vladimir','Morozov','Canoe / Kayak F');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (13877,'Dezs√∂','Novak','Football');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (14906,'Pedro','Petrone','Football');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (15257,'Elena','Posevina','Rhythmic G.');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (17145,'Briana','Scurry','Football');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (17367,'James','Shepherd','Tug of War');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (17373,'Natalia','Sherstyuk-Timoshkina','Handball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (17815,'Katie','Smith','Basketball');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (21622,'Leontien','Zijlaard-Van Moorsel','Cycling Road');
Insert into olympics.QUES3 (AID,FNAME,LNAME,SPORT) values (21071,'Allan','Woodman','Ice Hockey');
