Insert into olympics.QUES2 (AID,FNAME,LNAME) values (540,' Kalle','Anttila');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (9604,' Charles','Kiraly');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (21622,' Leontien','Zijlaard-Van Moorsel');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (10624,' Guy','Lapebie');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (20642,' Johnny','Weissmuller');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (19093,' Earl Foster','Thomson');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (7811,' Henri','Hoevenaers');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (12624,' DÃ©sirÃ©','Merchez');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (10988,' Tommaso','Lequio Di Assaba');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (15950,' Aileen','Riggin');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (17342,' Timothy Andrew','Shaw');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (2957,' Harry Dwight','Chamberlin');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (19778,' Jean','Van Den Bosch');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (20547,' Kathryn Anne','Watt');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (13575,' Ago (August)','Neo');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (7823,' Georg','Hoffmann');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (12513,' Aleksandr','Medved');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (15523,' Erich','Rademacher');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (312,' Alessandro','Alvisi');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (15539,' Paul','Radmilovic');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (17750,' Olga','Slyusareva');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (6928,' Boris','Gurevich');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (9121,' Jan','Karlsson');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (378,' Olle','Anderberg');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (1502,' Per Gunnar','Berlin');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (622,' Judith','Arndt');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (7259,' Pontus','Hansson');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (19557,' Rebecca Lynne','Twigg');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (3286,' Austin Rhone','Clapp');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (898,' Karoly','Bajko');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (11602,' Age','Lundstrã–M');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (10906,' Guy Robert Marie','Lefrant');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (6528,' Leo Budd','Goodwin');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (4946,' Vyacheslav','Ekimov');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (15701,' Katherine Louise','Rawls');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (4921,' Wolfgang','Ehrl');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (2610,' Giulio','Cacciandra');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (9015,' Henry Justaves','Kaltenbrun');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (531,' Michal','Antoniewicz');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (17986,' Frank William','Southall');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (20381,' Helen','Wainwright');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (20077,' Michel','Vermeulen');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (2750,' J','Cariou');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (9118,' Einar','Karlsson');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (18025,' Garibaldi','Spighi');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (17519,' Luiz','Silva');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (18565,' Rudolf','Svensson');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (1772,' Gerard','Blitz');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (12630,' Leonard Lewis','Meredith');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (13940,' Hjalmar Eemil','Nystrã–M');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (1795,' Christopher Miles','Boardman');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (7775,' Nikolaus','Hirschl');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (14412,' Kristjan','Palusalu');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (9615,' Ahmet','Kireã‡Ã‡I');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (20288,' Clarence','Von Rosen Jr.');
Insert into olympics.QUES2 (AID,FNAME,LNAME) values (4022,' ClaÃ«s','De Kã–Nig');