Insert into olympics.QUES6 (YEAR,COUNTRY) values (1896,'Germany');
Insert into olympics.QUES6 (YEAR,COUNTRY) values (1936,'Germany');
Insert into olympics.QUES6 (YEAR,COUNTRY) values (1980,'Russia');
Insert into olympics.QUES6 (YEAR,COUNTRY) values (1988,'Russia');
Insert into olympics.QUES6 (YEAR,COUNTRY) values (1976,'Russia');
Insert into olympics.QUES6 (YEAR,COUNTRY) values (1972,'Russia');
Insert into olympics.QUES6 (YEAR,COUNTRY) values (1912,'Sweden');
Insert into olympics.QUES6 (YEAR,COUNTRY) values (1908,'United Kingdom');
Insert into olympics.QUES6 (YEAR,COUNTRY) values (1900,'United Kingdom');
Insert into olympics.QUES6 (YEAR,COUNTRY) values (2008,'United States');
Insert into olympics.QUES6 (YEAR,COUNTRY) values (1952,'United States');
Insert into olympics.QUES6 (YEAR,COUNTRY) values (1932,'United States');
Insert into olympics.QUES6 (YEAR,COUNTRY) values (1904,'United States');
Insert into olympics.QUES6 (YEAR,COUNTRY) values (1996,'United States');
Insert into olympics.QUES6 (YEAR,COUNTRY) values (1984,'United States');
Insert into olympics.QUES6 (YEAR,COUNTRY) values (1964,'United States');
Insert into olympics.QUES6 (YEAR,COUNTRY) values (1960,'United States');
Insert into olympics.QUES6 (YEAR,COUNTRY) values (1924,'United States');
Insert into olympics.QUES6 (YEAR,COUNTRY) values (1920,'United States');
Insert into olympics.QUES6 (YEAR,COUNTRY) values (1956,'United States');
Insert into olympics.QUES6 (YEAR,COUNTRY) values (1948,'United States');
Insert into olympics.QUES6 (YEAR,COUNTRY) values (1928,'United States');
Insert into olympics.QUES6 (YEAR,COUNTRY) values (2000,'United States');
Insert into olympics.QUES6 (YEAR,COUNTRY) values (2004,'United States');
Insert into olympics.QUES6 (YEAR,COUNTRY) values (1968,'United States');
Insert into olympics.QUES6 (YEAR,COUNTRY) values (1992,'Unified Team');
