Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Gre-R','Denmark',1908);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Athletics','United States',1932);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Hockey','Netherlands',1928);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Judo','Japan',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Fencing','Italy',1928);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Basketball','United States',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Eventing','United States',1932);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rowing','United States',1904);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Diving','United States',1904);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Diving','Sweden',1912);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Baseball','Japan',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Tennis','United Kingdom',1912);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Track','Australia',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Volleyball','Russia',1980);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Eventing','Germany',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Handball','Germany',1936);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Swimming','United States',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rowing','United States',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Canoe / Kayak S','Germany',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Diving','United States',1928);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','United States',1904);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rowing','East Germany',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Fencing','Hungary',1912);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Sailing','United States',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Football','France',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Boxing','Italy',1960);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Sailing','United States',1932);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Athletics','United States',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Shooting','Unified Team',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','Turkey',1960);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Water polo','United States',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Hockey','United Kingdom',1908);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Gre-R','Russia',1968);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Canoe / Kayak F','Hungary',1960);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Gre-R','Russia',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling','United Kingdom',1908);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Polo','United Kingdom',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Sailing','United States',1968);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Water polo','Hungary',1932);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Football','United States',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Sailing','France',1900);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Swimming','United States',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Hockey','Denmark',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Gre-R','Russia',1980);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Athletics','United States',1936);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Volleyball','Netherlands',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Eventing','Russia',1980);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Canoe / Kayak F','Germany',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','United Kingdom',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','Poland',1980);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Sailing','Norway',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Hockey','United States',1932);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rowing','East Germany',1980);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Diving','United States',1976);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Judo','Russia',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Water polo','Russia',1968);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Boxing','United States',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Water polo','Hungary',1956);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Canoe / Kayak F','Russia',1956);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Football','Denmark',1912);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Tug of War','United Kingdom',1912);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Track','France',1936);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Table Tennis','China',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Handball','Korea, South',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Eventing','New Zealand',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Athletics','United States',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Canoe / Kayak F','Czechoclovakia',1948);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Taekwondo','Australia',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','United States',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Hockey','United Kingdom',1952);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','United States',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Shooting','East Germany',1980);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Weightlifting','Belgium',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Eventing','Netherlands',1928);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Canoe / Kayak F','Hungary',1968);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Figure skating','United Kingdom',1908);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','Poland',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Eventing','Sweden',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','Sweden',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','Germany',1912);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Mountain Bike','United States',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Fencing','Cuba',1904);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Eventing','Germany',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Track','Italy',1956);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Badminton','China',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','Sweden',1968);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Swimming','Germany',1900);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','Switzerland',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Archery','France',1900);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Eventing','United Kingdom',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Boxing','Canada',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Synchronized S.','Japan',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Table Tennis','China',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Shooting','Germany',1936);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','Germany',1936);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Football','Denmark',1948);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','United Kingdom',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Softball','Japan',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Baseball','Japan',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Eventing','Australia',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Judo','Japan',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Swimming','United States',1952);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','Russia',1960);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Basketball','Russia',1960);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Shooting','Russia',1968);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Diving','United States',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','United States',1936);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jeu de Paume','United Kingdom',1908);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','Poland',1976);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','Russia',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','Germany',1976);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Eventing','United States',1968);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','Lithuania',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling','United Kingdom',1952);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Mountain Bike','Switzerland',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','Russia',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Mountain Bike','Germany',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Handball','Denmark',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Athletics','United States',1928);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','Poland',1928);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Football','Spain',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Boxing','Cuba',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Tug of War','Mulitple Nations',1900);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Hockey','Netherlands',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Football','Norway',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Fencing','Italy',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Football','Ghana',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Sailing','United States',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Sailing','United Kingdom',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Track','Australia',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Weightlifting','Russia',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rugby','Germany',1900);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Table Tennis','Korea, South',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Sailing','United States',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Athletics','United States',1968);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Basketball','Yugoslavia',1980);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Diving','United States',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rowing','United States',1956);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Football','Italy',1928);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Swimming','United States',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Weightlifting','Russia',1968);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Eventing','Australia',1976);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rowing','United Kingdom',1912);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Volleyball','Russia',1976);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Artistic G.','Sweden',1908);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Sailing','Australia',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Artistic G.','Russia',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Artistic G.','Russia',1956);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Boxing','Cuba',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Football','Italy',1936);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Football','Hungary',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Gre-R','Russia',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Football','United States',1904);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Football','Italy',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Fencing','Russia',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Shooting','Belarus',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Tug of War','France',1900);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Basketball','Russia',1956);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Water polo','Hungary',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Gre-R','Russia',1960);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Shooting','Russia',1956);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Weightlifting','Russia',1956);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Water polo','Hungary',1948);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','Germany',1936);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','United Kingdom',1956);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Dressage','Sweden',1952);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Football','Russia',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Track','Netherlands',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Weightlifting','China',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Baseball','Korea, South',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Track','France',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Figure skating','Norway',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Polo','United Kingdom',1908);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Water polo','France',1928);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Synchronized S.','Spain',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Tug of War','United Kingdom',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Boxing','Cuba',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rowing','Germany',1900);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Swimming','United States',1948);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Taekwondo','Korea, South',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Diving','United States',1956);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('BMX','United States',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Eventing','Netherlands',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Water polo','Hungary',1980);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Boxing','United Kingdom',1908);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Gre-R','Russia',1956);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Weightlifting','Egypt',1936);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Judo','Japan',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Gre-R','Unified Team',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Boxing','Russia',1980);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Table Tennis','China',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Boxing','Russia',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','Netherlands',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Artistic G.','Russia',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Badminton','China',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Shooting','China',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Diving','China',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Diving','China',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Fencing','Hungary',1908);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Track','France',1896);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Weightlifting','Russia',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Boxing','Cuba',1980);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','Iran',1968);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Track','United States',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Baseball','Japan',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','Russia',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Diving','China',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Badminton','Korea, South',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Weightlifting','Switzerland',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Judo','Japan',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Swimming','Japan',1932);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Mountain Bike','Spain',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Sailing','Sweden',1928);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Sailing','United States',1960);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Dressage','Russia',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling','Turkey',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Polo','Argentina',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Judo','Russia',1980);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','Russia',1968);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Eventing','New Zealand',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','Lithuania',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','Germany',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Diving','China',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','United Kingdom',1952);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling','Russia',1968);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Shooting','Russia',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','Sweden',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling','United States',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','Russia',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Gre-R','Poland',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Beach volley.','China',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Synchronized S.','Japan',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Water Motorspor','United Kingdom',1908);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Mountain Bike','Italy',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling','Switzerland',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','Latvia',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Artistic G.','Denmark',1912);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Shooting','United States',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Basketball','Russia',1968);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Football','Yugoslavia',1960);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Fencing','Italy',1932);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Basketball','United States',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Volleyball','Russia',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Hockey','Germany',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Sailing','Norway',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Golf','United States',1900);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Baseball','United States',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Sailing','United Kingdom',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Handball','Korea, South',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Football','East Germany',1980);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Hockey','Germany',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Athletics','United States',1900);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Tennis','United Kingdom',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Beach volley.','Brazil',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Handball','Spain',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Volleyball','Russia',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Athletics','United States',1956);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','Russia',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Basketball','Russia',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Softball','United States',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Fencing','Italy',1952);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Artistic G.','Russia',1960);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Boxing','Argentina',1928);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rowing','Germany',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rowing','East Germany',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Diving','United States',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Water polo','Croatia',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Basketball','United States',1936);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Track','United Kingdom',1948);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Football','Russia',1956);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Tug of War','United States',1904);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Fencing','France',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Basketball','United States',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Swimming','Australia',1956);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','United States',1960);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Diving','China',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Fencing','Russia',1968);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Handball','Korea, South',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Gre-R','Greece',1896);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Canoe / Kayak F','Russia',1976);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Eventing','United Kingdom',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rowing','United States',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Athletics','United States',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Badminton','Indonesia',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Weightlifting','Russia',1960);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','Switzerland',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Ice Hockey','United States',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Track','Belgium',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Football','Hungary',1960);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Water polo','Belgium',1900);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Archery','Belgium',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Swimming','France',1900);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Eventing','Australia',1968);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','Russia',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Eventing','Germany',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Sailing','Norway',1936);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling','Bulgaria',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','Russia',1976);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Trampoline','China',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Gre-R','Finland',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Sailing','Brazil',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Track','Germany',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Dressage','Switzerland',1960);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Artistic G.','Germany',1896);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','United States',1936);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Badminton','China',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Gre-R','Italy',1932);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Synchronized S.','Japan',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Artistic G.','Switzerland',1928);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Boxing','Russia',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Dressage','Germany',1936);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Diving','East Germany',1980);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','Belgium',1900);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Judo','East Germany',1980);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Badminton','China',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Canoe / Kayak S','Czech Republic',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling','Austria',1932);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Dressage','Switzerland',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Judo','Japan',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','Canada',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Tennis','United States',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','Russia',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','Sweden',1932);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling','Russia',1952);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Shooting','Italy',1932);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Archery','United States',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Judo','Russia',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','Sweden',1932);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling','United States',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Handball','Denmark',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Water polo','Hungary',1952);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Beach volley.','Brazil',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Hockey','New Zealand',1976);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','United States',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Hockey','Pakistan',1960);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Hockey','Pakistan',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','Russia',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Volleyball','Russia',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Volleyball','Russia',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','Czechoclovakia',1976);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Canoe / Kayak S','France',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Athletics','United States',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Swimming','United States',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Athletics','East Germany',1976);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Handball','Unified Team',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','Germany',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Beach volley.','Brazil',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','Germany',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Artistic G.','Unified Team',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Athletics','United States',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rhythmic G.','Russia',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','Hungary',1952);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Shooting','Sweden',1912);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Handball','Czechoclovakia',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Athletics','United States',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Swimming','United States',1960);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Swimming','United States',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Basketball','Brazil',1948);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Boxing','United States',1904);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Sailing','Sweden',1912);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Water polo','United States',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Athletics','United States',1952);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Shooting','Russia',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Athletics','Jamaica',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Gre-R','Russia',1976);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rowing','Australia',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Boxing','Italy',1948);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Tennis','United Kingdom',1908);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Weightlifting','Bulgaria',1980);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Swimming','United States',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Football','Russia',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling','Hungary',1948);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rowing','Russia',1968);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Archery','United Kingdom',1908);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','Portugal',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Water polo','Russia',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Track','France',1932);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Football','United Kingdom',1900);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Weightlifting','China',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Boxing','Russia',1968);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Fencing','Russia',1960);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Water polo','Russia',1960);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Judo','Russia',1976);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Canoe / Kayak F','Russia',1980);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Hockey','India',1948);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Tennis','Spain',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Artistic G.','Russia',1968);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Archery','Russia',1980);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Canoe / Kayak F','Germany',1936);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Fencing','France',1896);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Shooting','United States',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Tennis','United States',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Eventing','United States',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Boxing','United States',1976);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Weightlifting','United States',1948);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Basque Pelota','Spain',1900);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','Sweden',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Golf','United States',1904);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Trampoline','Canada',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Judo','Japan',1976);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','Italy',1960);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Artistic G.','Russia',1976);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Trampoline','Germany',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Boxing','United Kingdom',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Diving','China',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Swimming','United States',1904);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','Mexico',1980);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Football','Germany',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','Bulgaria',1968);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Track','East Germany',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','France',1956);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Gre-R','Russia',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','Finland',1928);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Diving','United States',1960);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','United Kingdom',1912);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling','United States',1904);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Taekwondo','Korea, South',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Canoe / Kayak F','Finland',1952);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Canoe / Kayak S','Slovakia',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Eventing','United Kingdom',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Gre-R','Sweden',1936);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','Russia',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','Greece',1896);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Judo','Japan',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Synchronized S.','Japan',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Shooting','East Germany',1976);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Dressage','Germany',1968);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Diving','Sweden',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Gre-R','Finland',1928);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Weightlifting','United States',1904);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Diving','Unified Team',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','United Kingdom',1928);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Eventing','Australia',1960);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','Sweden',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Dressage','Germany',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Eventing','Germany',1936);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Triathlon','Switzerland',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Dressage','Netherlands',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Track','France',1968);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Tennis','United States',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Mountain Bike','Poland',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','Unified Team',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling','United States',1932);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Weightlifting','Sweden',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling','Finland',1928);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling','Finland',1936);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling','Estonia',1936);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Handball','Yugoslavia',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Artistic G.','Denmark',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Handball','Russia',1976);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling','Sweden',1948);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Basketball','Yugoslavia',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','Russia',1980);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Judo','Cuba',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','Italy',1936);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Fencing','Russia',1980);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Athletics','Russia',1980);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Canoe / Kayak F','Germany',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Volleyball','Brazil',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','East Germany',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Canoe / Kayak S','Germany',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Swimming','United States',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Volleyball','United States',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Weightlifting','Romania',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Hockey','Germany',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Canoe / Kayak S','Germany',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Hockey','Belgium',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Fencing','Germany',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Hockey','Australia',1976);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Artistic G.','Russia',1952);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Softball','United States',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Weightlifting','Russia',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Athletics','United States',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Artistic G.','Russia',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rugby','United States',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Synchronized S.','Russia',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Basketball','United States',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Swimming','United States',1976);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Athletics','United States',1960);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rhythmic G.','Belarus',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Basketball','Russia',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Water polo','Spain',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rowing','Italy',1932);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Fencing','Hungary',1956);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Canoe / Kayak F','United States',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Eventing','Germany',1952);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Artistic G.','Hungary',1948);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Synchronized S.','United States',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Artistic G.','United States',1932);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Track','France',1900);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','United Kingdom',1896);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Swimming','United Kingdom',1912);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Fencing','Germany',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Artistic G.','United States',1904);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Athletics','United States',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Lacrosse','Canada',1904);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Mountain Bike','Switzerland',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Canoe / Kayak F','Germany',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Polo','United States',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rowing','Australia',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Eventing','United Kingdom',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Fencing','France',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rowing','United States',1948);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Water polo','Belgium',1908);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Dressage','Germany',1976);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Weightlifting','Italy',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','France',1948);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Track','Italy',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Artistic G.','Russia',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Weightlifting','China',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Shooting','China',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Weightlifting','Russia',1952);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Archery','Korea, South',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Track','United Kingdom',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Diving','United States',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Hockey','India',1956);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Dressage','France',1948);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Diving','United States',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rowing','United States',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','France',1912);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Fencing','Italy',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Sailing','United States',1976);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Shooting','United States',1948);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Eventing','United Kingdom',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Tennis','United Kingdom',1900);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Boxing','Argentina',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Synchronized S.','Russia',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Dressage','Sweden',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Hockey','Australia',1968);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','Belgium',1976);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Fencing','France',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Dressage','United States',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Handball','Croatia',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Tennis','Chile',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Diving','United States',1968);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Softball','Japan',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rhythmic G.','Canada',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Gre-R','Germany',1928);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Shooting','Russia',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','Unified Team',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','United Kingdom',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Boxing','Cuba',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Canoe / Kayak S','Slovakia',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Weightlifting','Denmark',1896);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','United States',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Fencing','Greece',1896);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','Russia',1980);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Gre-R','Russia',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Mountain Bike','Russia',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Dressage','United States',1956);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Weightlifting','Russia',1976);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Archery','Russia',1976);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Taekwondo','Korea, South',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Synchronized S.','Japan',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','Sweden',1928);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Diving','United States',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rhythmic G.','Romania',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Diving','United States',1952);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Sailing','United Kingdom',1968);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling','Sweden',1952);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Volleyball','Russia',1968);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Gre-R','Finland',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Basketball','United States',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Canoe / Kayak F','Hungary',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Mountain Bike','France',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Sailing','United Kingdom',1908);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Boxing','Poland',1960);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rowing','East Germany',1976);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Weightlifting','Austria',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','Turkey',1948);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','Russia',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Water polo','Russia',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','United States',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rowing','United States',1928);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Track','Australia',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Swimming','United States',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Water polo','Yugoslavia',1980);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Volleyball','United States',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Diving','Germany',1908);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Basketball','Russia',1976);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Gre-R','Russia',1952);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Football','Poland',1976);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Hockey','United Kingdom',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Fencing','Russia',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','Sweden',1912);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Athletics','United States',1904);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Artistic G.','Russia',1980);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','Switzerland',1928);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Canoe / Kayak S','East Germany',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Water polo','Germany',1936);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Shooting','United States',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','Hungary',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Boxing','Russia',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Athletics','United States',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Football','United States',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Dressage','Netherlands',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rhythmic G.','Russia',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Basketball','United States',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rowing','Canada',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Football','Hungary',1952);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Track','Netherlands',1928);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Hockey','Netherlands',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Hockey','Netherlands',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Dressage','Sweden',1912);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Canoe / Kayak F','Hungary',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Handball','East Germany',1980);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Track','France',1956);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','United States',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','Bulgaria',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Canoe / Kayak F','Russia',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Archery','Korea, South',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Swimming','Greece',1896);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Swimming','United States',1928);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Track','United Kingdom',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Water polo','United Kingdom',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Synchronized S.','Canada',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','Czech Republic',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','United Kingdom',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Mountain Bike','Norway',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling','France',1928);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Polo','Spain',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','United States',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Synchronized S.','United States',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','Canada',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rowing','United States',1952);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling','Russia',1960);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Track','Russia',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Softball','Japan',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Boxing','Russia',1956);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Shooting','Russia',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','Sweden',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Eventing','Sweden',1952);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Mountain Bike','Switzerland',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Tennis','United States',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Sailing','United States',1948);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Shooting','Switzerland',1948);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Gre-R','Russia',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Table Tennis','China',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Weightlifting','Germany',1928);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','Denmark',1928);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','Belgium',1952);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','Iran',1952);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','Russia',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','Spain',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Judo','Japan',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Canoe / Kayak S','Czech Republic',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','United States',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Canoe / Kayak S','Slovakia',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','Japan',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','Mongolia',1968);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Track','United Kingdom',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Shooting','Greece',1896);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','France',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','France',1968);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling','Finland',1956);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Archery','Korea, South',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Diving','East Germany',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','United States',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','Finland',1932);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Dressage','Russia',1980);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','United Kingdom',1948);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Shooting','China',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rhythmic G.','Russia',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','Italy',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling','Bulgaria',1956);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','United States',1952);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Dressage','United States',1960);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','Germany',1968);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','Russia',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Boxing','Italy',1928);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling','Sweden',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','Japan',1932);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Mountain Bike','Canada',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','Italy',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Football','Poland',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Gre-R','Romania',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Football','Yugoslavia',1956);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Swimming','Japan',1936);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Hockey','Pakistan',1976);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','United States',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Boxing','Cuba',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Eventing','Sweden',1912);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Swimming','United States',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rowing','United States',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Swimming','United States',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Handball','Russia',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','United Kingdom',1908);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Artistic G.','Germany',1936);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','Germany',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Track','Italy',1960);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Hockey','Germany',1936);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Water polo','Hungary',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Canoe / Kayak F','Sweden',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Athletics','United States',1948);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Water polo','United Kingdom',1912);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Sailing','United States',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Sailing','Denmark',1960);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Shooting','United States',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Weightlifting','France',1928);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rackets','United Kingdom',1908);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Fencing','France',1900);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rowing','Germany',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Synchronized S.','United States',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Hockey','India',1932);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Dressage','Germany',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Swimming','United States',1968);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Shooting','France',1900);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Shooting','Hungary',1952);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Swimming','East Germany',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Track','United Kingdom',1908);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Artistic G.','France',1900);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Sailing','United Kingdom',1956);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rowing','United Kingdom',1908);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Shooting','United Kingdom',1908);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Football','Denmark',1908);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Sailing','United States',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Football','Germany',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Gre-R','Germany',1932);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Tennis','Mulitple Nations',1896);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Dressage','United States',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Dressage','Sweden',1956);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Shooting','Russia',1960);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Vaulting','Belgium',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Polo','Mulitple Nations',1900);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Water polo','France',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Weightlifting','Bulgaria',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Artistic G.','United States',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Water polo','Germany',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','United States',1932);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Sailing','United States',1952);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Football','Bulgaria',1968);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Archery','United States',1904);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','Switzerland',1936);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Boxing','Russia',1952);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Artistic G.','Russia',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Fencing','Russia',1976);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Basketball','Russia',1952);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','France',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Dressage','Germany',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','Sweden',1928);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','United Kingdom',1948);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rugby','United States',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Boxing','United States',1928);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rugby','United Kingdom',1908);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Dressage','Switzerland',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Track','Italy',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Water polo','Hungary',1976);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Swimming','East Germany',1980);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Weightlifting','Greece',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','Italy',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Gre-R','Russia',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','Belarus',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Eventing','United States',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Dressage','Spain',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','Sweden',1948);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Artistic G.','Switzerland',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Boxing','Cuba',1976);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','Finland',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','Japan',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Hockey','Japan',1932);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Weightlifting','Germany',1932);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','Belgium',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Trampoline','Russia',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Archery','Korea, South',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Synchronized S.','United States',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','Germany',1928);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Archery','Korea, South',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Archery','Korea, South',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Track','Russia',1980);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Diving','United States',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Dressage','United States',1932);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling','Czechoclovakia',1936);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','Germany',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Track','Poland',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','Netherlands',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','Canada',1928);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Dressage','Germany',1928);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','Italy',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Tennis','Czechoclovakia',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','United States',1932);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling','Switzerland',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling','Sweden',1928);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling','Sweden',1932);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Eventing','Sweden',1948);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Tennis','Czech Republic',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Mountain Bike','Canada',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Beach volley.','Brazil',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Gre-R','Sweden',1948);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Diving','United States',1948);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Water polo','Russia',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rowing','Germany',1936);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Hockey','Australia',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Football','Switzerland',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Mountain Bike','France',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Athletics','United States',1912);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Hockey','Russia',1980);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rugby','France',1900);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Weightlifting','Unified Team',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','Italy',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','United States',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','United States',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cricket','United Kingdom',1900);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Water polo','United States',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rowing','United Kingdom',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Hockey','Germany',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Fencing','Russia',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Tennis','United States',1904);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rhythmic G.','Russia',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Football','Czechoclovakia',1980);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Volleyball','Italy',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Gre-R','Finland',1912);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Badminton','Indonesia',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Shooting','United States',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Athletics','Russia',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rowing','United States',1960);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Sailing','Russia',1980);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','Russia',1956);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','Hungary',1960);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Boxing','United States',1968);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Handball','Croatia',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Artistic G.','Romania',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Tug of War','United Kingdom',1908);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Canoe / Kayak F','Hungary',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Boxing','United States',1932);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Swimming','United Kingdom',1908);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Track','United States',1904);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Athletics','United States',1896);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Canoe / Kayak F','East Germany',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Lacrosse','United Kingdom',1908);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Fencing','Italy',1936);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Boxing','United States',1988);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Eventing','United Kingdom',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Track','Germany',1976);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Swimming','United States',1956);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Hockey','Netherlands',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Roque','United States',1904);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Water polo','Hungary',1960);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Volleyball','Russia',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Athletics','United States',1908);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Dressage','Switzerland',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Artistic G.','China',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Artistic G.','China',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Judo','Russia',1972);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Tennis','United States',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Fencing','France',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Track','Italy',1952);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Fencing','Italy',1948);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Tennis','United States',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Triathlon','New Zealand',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','Italy',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Polo','United Kingdom',1936);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Diving','United States',1932);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Diving','United States',1936);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Jumping','Italy',1956);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Beach volley.','United States',1996);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Football','Austria',1936);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','Germany',1896);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling','Russia',1964);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Free.','Sweden',1932);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','Finland',1956);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Shooting','Sweden',1948);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Boxing','Germany',1936);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling Gre-R','Finland',1932);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling','Turkey',1956);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling','Turkey',1960);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Table Tennis','China',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Archery','Korea, South',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','Russia',1980);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Eventing','United States',1956);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Vaulting','Sweden',1920);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Wrestling','United Kingdom',1924);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Archery','United States',1984);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Taekwondo','Cuba',2000);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Triathlon','Australia',2008);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Cycling Road','Italy',1932);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Rhythmic G.','Unified Team',1992);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Eventing','Germany',1912);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Modern Pentath.','Hungary',2004);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Weightlifting','Greece',1896);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Archery','United States',1976);
Insert into olympics.QUES5 (SPORT,COUNTRY,YEAR) values ('Mountain Bike','Germany',2004);
